/* src/Teko_config.h.in.  Generated by me! */

/* For enabling probing */
#define Teko_ENABLE_Isorropia

/* For development mode */
/* #undef Teko_ENABLE_DEV_MODE */
/* #undef Teko_ENABLE_ML_SMOOTHERS */
