# Generated by CMake 2.8.12.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget teuchoscore teuchosparameterlist teuchoscomm teuchosnumerics teuchosremainder tpi sacado rtop kokkos kokkosnodeapi kokkoslinalg kokkosnodetsqr kokkosdisttsqr epetra zoltan triutils tpetra tpetrainout tpetraext epetraext xpetra xpetra-ext xpetra-sup thyracore thyraepetra thyraepetraext thyratpetra isorropia aztecoo galeri galeri-xpetra amesos ifpack ml belos belosepetra belostpetra anasazi anasaziepetra ModeLaplace anasazitpetra shylu stratimikosifpack stratimikosml stratimikosamesos stratimikosaztecoo stratimikosbelos stratimikos teko nox noxlapack noxepetra loca localapack locaepetra locathyra rythmos)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Create imported target teuchoscore
add_library(teuchoscore STATIC IMPORTED)

# Create imported target teuchosparameterlist
add_library(teuchosparameterlist STATIC IMPORTED)

# Create imported target teuchoscomm
add_library(teuchoscomm STATIC IMPORTED)

# Create imported target teuchosnumerics
add_library(teuchosnumerics STATIC IMPORTED)

# Create imported target teuchosremainder
add_library(teuchosremainder STATIC IMPORTED)

# Create imported target tpi
add_library(tpi STATIC IMPORTED)

# Create imported target sacado
add_library(sacado STATIC IMPORTED)

# Create imported target rtop
add_library(rtop STATIC IMPORTED)

# Create imported target kokkos
add_library(kokkos STATIC IMPORTED)

# Create imported target kokkosnodeapi
add_library(kokkosnodeapi STATIC IMPORTED)

# Create imported target kokkoslinalg
add_library(kokkoslinalg STATIC IMPORTED)

# Create imported target kokkosnodetsqr
add_library(kokkosnodetsqr STATIC IMPORTED)

# Create imported target kokkosdisttsqr
add_library(kokkosdisttsqr STATIC IMPORTED)

# Create imported target epetra
add_library(epetra STATIC IMPORTED)

# Create imported target zoltan
add_library(zoltan STATIC IMPORTED)

# Create imported target triutils
add_library(triutils STATIC IMPORTED)

# Create imported target tpetra
add_library(tpetra STATIC IMPORTED)

# Create imported target tpetrainout
add_library(tpetrainout STATIC IMPORTED)

# Create imported target tpetraext
add_library(tpetraext STATIC IMPORTED)

# Create imported target epetraext
add_library(epetraext STATIC IMPORTED)

# Create imported target xpetra
add_library(xpetra STATIC IMPORTED)

# Create imported target xpetra-ext
add_library(xpetra-ext STATIC IMPORTED)

# Create imported target xpetra-sup
add_library(xpetra-sup STATIC IMPORTED)

# Create imported target thyracore
add_library(thyracore STATIC IMPORTED)

# Create imported target thyraepetra
add_library(thyraepetra STATIC IMPORTED)

# Create imported target thyraepetraext
add_library(thyraepetraext STATIC IMPORTED)

# Create imported target thyratpetra
add_library(thyratpetra STATIC IMPORTED)

# Create imported target isorropia
add_library(isorropia STATIC IMPORTED)

# Create imported target aztecoo
add_library(aztecoo STATIC IMPORTED)

# Create imported target galeri
add_library(galeri STATIC IMPORTED)

# Create imported target galeri-xpetra
add_library(galeri-xpetra STATIC IMPORTED)

# Create imported target amesos
add_library(amesos STATIC IMPORTED)

# Create imported target ifpack
add_library(ifpack STATIC IMPORTED)

# Create imported target ml
add_library(ml STATIC IMPORTED)

# Create imported target belos
add_library(belos STATIC IMPORTED)

# Create imported target belosepetra
add_library(belosepetra STATIC IMPORTED)

# Create imported target belostpetra
add_library(belostpetra STATIC IMPORTED)

# Create imported target anasazi
add_library(anasazi STATIC IMPORTED)

# Create imported target anasaziepetra
add_library(anasaziepetra STATIC IMPORTED)

# Create imported target ModeLaplace
add_library(ModeLaplace STATIC IMPORTED)

# Create imported target anasazitpetra
add_library(anasazitpetra STATIC IMPORTED)

# Create imported target shylu
add_library(shylu STATIC IMPORTED)

# Create imported target stratimikosifpack
add_library(stratimikosifpack STATIC IMPORTED)

# Create imported target stratimikosml
add_library(stratimikosml STATIC IMPORTED)

# Create imported target stratimikosamesos
add_library(stratimikosamesos STATIC IMPORTED)

# Create imported target stratimikosaztecoo
add_library(stratimikosaztecoo STATIC IMPORTED)

# Create imported target stratimikosbelos
add_library(stratimikosbelos STATIC IMPORTED)

# Create imported target stratimikos
add_library(stratimikos STATIC IMPORTED)

# Create imported target teko
add_library(teko STATIC IMPORTED)

# Create imported target nox
add_library(nox STATIC IMPORTED)

# Create imported target noxlapack
add_library(noxlapack STATIC IMPORTED)

# Create imported target noxepetra
add_library(noxepetra STATIC IMPORTED)

# Create imported target loca
add_library(loca STATIC IMPORTED)

# Create imported target localapack
add_library(localapack STATIC IMPORTED)

# Create imported target locaepetra
add_library(locaepetra STATIC IMPORTED)

# Create imported target locathyra
add_library(locathyra STATIC IMPORTED)

# Create imported target rythmos
add_library(rythmos STATIC IMPORTED)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/TrilinosTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
